### ISSUE TITLE
network problem when using 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by tuxun** [niklasf/lila-gif#15]
Hi, today, I saw someone struggle 2h30 to set this application because 127.0.0.1 was used instead of 0.0.0.0 in main.rs

you can see this on https://www.twitch.tv/videos/635148825 

i think it start around 1h05 of video and he fix it at 3h40 of video. 

Could you add a note **IN BOLD** somewhere in the readme, please?

(this post saved us: https://stackoverflow.com/a/58802065/3429116 )

**Comment by tuxun** [comment]
do whatever your want, but readme still don't mention we shouldn't use 127.0.0.1 if we need to network from something else than localhost

**Comment by niklasf** [comment]
Frankly this is the expected and safe default. Calling some attention to `--address` and `--port` will hopefully do.
